config/routes.rb
Rails.application.routes.draw do

  resources :addresses, :orders
  devise_for :users, controllers: {registrations: "registrations"}

  root "pages#home"

  get "/how_it_works" => "pages#how_it_works"

  get "/account" => "pages#account"

  post "/payment" => "orders#payment"

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :address
  belongs_to :user


  def price
    quantity * 3
  end

  def vat
    price * 0.2
  end

  def total
    price + vat
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :addresses

  def fullname
    [first_name, last_name].join(" ")
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :set_address, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = Address.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = Address.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    # @address = Address.new(address_params)
    @address = current_user.addresses.new(address_params)
    current_user.save

    respond_to do |format|
      if @address.save
        format.html { redirect_to @address, notice: 'Address was successfully created.' }
        format.json { render :show, status: :created, location: @address }
      else
        format.html { render :new }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to @address, notice: 'Address was successfully updated.' }
        format.json { render :show, status: :ok, location: @address }
      else
        format.html { render :edit }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to addresses_url, notice: 'Address was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = Address.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:telephone, :address_line_1, :address_line_2, :city, :county, :post_code, :country, :delivery_notes, :company_name, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  # my custom fields are :username, :first_name, :last_name
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:username, :first_name, :last_name,
        :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.for(:account_update) do |u|
      u.permit(:username, :first_name, :last_name,
        :email, :password, :password_confirmation, :current_password)
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def payment
    # Amount in pence
    order = Order.find(params[:order_id])

    ## if !order
      ## redirect_to...

    amount = (order.total * 100).to_i

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => amount,
      :description => 'Beer Order From DeskBrews',
      :currency    => 'gbp'
    )

    redirect_to account_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
    
  end

  def get_delivery_dates
    # this below is the functions and methods for creating the date to be friday
    # in order to use the method Date.today, you need to require "date" like above
    today = Date.today
    # this function is making daysUntilNextFrdiday 5 minus today
    daysUntilNextFriday = 5 - today.cwday;

    # if the days until friday are less than 3 days, it will display the next fridays date
    if daysUntilNextFriday < 3
      daysUntilNextFriday = daysUntilNextFriday + 7
    end

    # 
    friday = today + daysUntilNextFriday
    #  this makes an array for the delivery dates
    deliveryDates = [];
    # this loops through the dates alowing you to see 5 different dates
    (0..4).each do |i|
      thisFriday = friday + (i*7)
      # this line below is necessary for making the date look pretty
      # for more info see this:
      # http://ruby-doc.org/stdlib-2.1.1/libdoc/date/rdoc/Date.html#method-i-strftime
      deliveryDates << [ thisFriday.strftime("%A %-d %b"), thisFriday ]
    end
    return deliveryDates


    # GErrys version of lines 49 <> 58
    # (0..4).map do |i|
    #   thisFriday = friday + (i*7)
    #   [ thisFriday.strftime("%A %-d %b"), thisFriday ]
    # end
  end

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @deliveryDates = get_delivery_dates
  end

  # GET /orders/1/edit
  def edit
    @deliveryDates = get_delivery_dates
  end

  # POST /orders
  # POST /orders.json
  def create
    # @order = Order.new(order_params)
    @order = current_user.orders.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:delivery_date, :address_id, :payment_success, :user_id, :quantity)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end

  def how_it_works

  end

  def account

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_in_path_for(resource)
    account_path
  end

  def after_sign_up_path_for(resource)
      account_path
  end

  def after_update_path_for(resource)
      account_path
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/addresses/_form.html.erb
<br>
<%= form_for(@address) do |f| %>
  <% if @address.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address.errors.count, "error") %> prohibited this address from being saved:</h2>

      <ul>
      <% @address.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-6 col-md-offset-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>New Address</h1>
      </div>
      <div class="panel-body">
        <div class="form-group">
          <%= f.label :company_name %><br>
          <%= f.text_field :company_name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :telephone %><br>
          <%= f.text_field :telephone, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :address_line_1 %><br>
          <%= f.text_field :address_line_1, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :address_line_2 %><br>
          <%= f.text_field :address_line_2, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :city %><br>
          <%= f.text_field :city, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :county %><br>
          <%= f.text_field :county, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :post_code %><br>
          <%= f.text_field :post_code, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :country %><br>
          <%= f.text_field :country, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :delivery_notes %><br>
          <%= f.text_area :delivery_notes, class: "form-control" %>
        </div>
        <div class="actions form-group">
          <%= f.submit class: "btn btn-default" %>
        </div>
      </div>
      <div class="panel-footer">
        <%= link_to 'Back', addresses_path %>
      </div>
    </div>
  </div>
<% end %>
<!-- </div> -->

app/views/addresses/edit.html.erb
<h1>Editing Address</h1>

<%= render 'form' %>

<%= link_to 'Show', @address %> |
<%= link_to 'Back', addresses_path %>

app/views/addresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Addresses</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Telephone</th>
      <th>Address line 1</th>
      <th>Address line 2</th>
      <th>City</th>
      <th>County</th>
      <th>Post code</th>
      <th>Country</th>
      <th>Delivery notes</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addresses.each do |address| %>
      <tr>
        <td><%= address.company_name %></td>
        <td><%= address.telephone %></td>
        <td><%= address.address_line_1 %></td>
        <td><%= address.address_line_2 %></td>
        <td><%= address.city %></td>
        <td><%= address.county %></td>
        <td><%= address.post_code %></td>
        <td><%= address.country %></td>
        <td><%= address.delivery_notes %></td>
        <td><%= address.user %></td>
        <td><%= link_to 'Show', address %></td>
        <td><%= link_to 'Edit', edit_address_path(address) %></td>
        <td><%= link_to 'Destroy', address, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address', new_address_path %>

app/views/addresses/new.html.erb
<div class="container"> 
<%= render 'form' %>
</div>

app/views/addresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @address.company_name %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @address.telephone %>
</p>

<p>
  <strong>Address line 1:</strong>
  <%= @address.address_line_1 %>
</p>

<p>
  <strong>Address line 2:</strong>
  <%= @address.address_line_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>

<p>
  <strong>County:</strong>
  <%= @address.county %>
</p>

<p>
  <strong>Post code:</strong>
  <%= @address.post_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @address.country %>
</p>

<p>
  <strong>Delivery notes:</strong>
  <%= @address.delivery_notes %>
</p>

<p>
  <strong>User:</strong>
  <%= @address.user.fullname %>
</p>

<%= link_to 'Edit', edit_address_path(@address) %> |
<%= link_to 'Back', addresses_path %>

app/views/application/_about.html.erb
<div class="container">
  <h1 class="about-header">HOW IT WORKS</h1>
  <div class="row" id="signup-icon">
    <div class="col-md-offset-2 col-lg-offset-3 col-md-8 col-lg-6">
      <div class="row">
        <div class="col-md-6 about">
          <h3>Sign Up To DeskBrews</h3>
        </div>
        <div class="col-md-6 img-icon">
          <%= image_tag "adaptive_design.png" %>
        </div>
      </div>
      <div class="row" id="date-icon">
        <div class="col-md-6 about">
          <h3>Choose Your Delivery Date</h3>
        </div>
        <div class="col-md-6 img-icon">
          <%= image_tag "calendar.png" %>        
        </div>
      </div>
      <div class="row" id="card-icon">
        <div class="col-md-6 about">
          <h3>Easy Credit Card Payment</h3>
        </div>
        <div class="col-md-6 img-icon">
          <%= image_tag "credit_card.png" %>
        </div>
      </div>
      <div class="row" id="transport-icon">
        <div class="col-md-6 about">
          <h3>Your Beers Will Be Delivered To You</h3>
        </div>
        <div class="col-md-6 img-icon">
          <%= image_tag "transport.png" %>
        </div>
      </div>
      <div class="row" id="beer-icon">
        <div class="col-md-6 about">
          <h3>Then Simply Enjoy!</h3>
        </div>
        <div class="col-md-6 img-icon">
          <%= image_tag "beer_icon.png" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_footer.html.erb
<div id="footer">
  <div class="container">
    <p>Made with <span class="redheart">&hearts;</span> By Gareth Gomersall | WDI-16 London </p>
  </div>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to (image_tag "logo.png"), root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "How It Works", how_it_works_path %></li>
        <% if user_signed_in?  %>
        <li><%= link_to "My Account", account_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deskbrews</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= render "navbar" %>


  <%= yield %> 

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <div class="form-group">
      <%= f.label :delivery_date %><br>
      <%= f.select :delivery_date, options_for_select(@deliveryDates, @order.delivery_date), {}, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :quantity %><br>
      <%= f.select :quantity, options_for_select([12, 24, 36, 48, 60], @order.quantity), {}, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :address_id %><br>
      <%= f.collection_select :address_id, current_user.addresses, :id, :company_name, { selected: @order.address_id }, class: "form-control" %>
    </div>
    <div>
      <h4>Your order summary is: </h4>
      
    </div>
    <br>
    <div class="actions form-group">
      <%= f.submit class: "btn btn-default" %>
    </div>
  </div>
<% end %>
    

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<br>
<div class="col-md-6 col-md-offset-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>Edit You Order</h1>
    </div>

    <%= render 'form' %>

    <div class="panel-footer">
      <%= link_to 'Show', @order %> |
      <%= link_to 'Back', orders_path %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Delivery date</th>
      <th>Address</th>
      <th>Payment success</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.delivery_date %></td>
        <td><%= order.address %></td>
        <td><%= order.payment_success %></td>
        <td><%= order.user %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<br>
<div class="col-md-6 col-md-offset-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h1>Order Some Beers</h1>
    </div>

    <%= render 'form' %>

    <div class="panel-footer">
      <%= link_to 'Back', orders_path %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<br>
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="panel panel-default">
    <div class="panel-heading">
        <h2>Order Summary</h2>
    </div>
    <div class="panel-body">
      <p>
        <strong>Delivery date:</strong>
        <%= @order.delivery_date %>
      </p>

      <p>
        <strong>Name:</strong>
        <%= @order.user.fullname %>
      </p>

      <p>
        <strong>Address:</strong>
        <%= @order.address.company_name %>
      </p>

      <p>
        <strong>Amount of Beers:</strong>
        <strong><%= @order.quantity %></strong>
      </p>

      <p>
        <h3>Total Payable: <%= number_to_currency(@order.total, unit: "£") %></h3><p> inclusive of VAT</p>
      </p>

      <%= form_tag payment_path, method: :post do %>
        <%= hidden_field_tag 'order_id', @order.id %>
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="Your Beer Order"
                  data-currency="gbp"
                  data-amount="<%= (@order.total * 100).to_i %>"
                  data-locale="auto"></script>
      <% end %>
    </div>

    <div class="panel-footer">
      <%= link_to 'Edit', edit_order_path(@order) %> |
      <%= link_to 'Back', orders_path %>
    </div>
  </div>
</div>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/pages/account.html.erb
<div class="container">
<!-- dynamic pills -->
  <div class="row center">
    <div class="col-md-2"></div>  
    <div class="col-md-2">
      <ul class="nav nav-pills nav-stacked">
        <li role="presentation" class="active"><a data-toggle="pill" href="#overview">Overview</a></li>
        <li role="presentation"><a data-toggle="pill" href="#order-history">Order History</a></li>
        <li role="presentation"><a data-toggle="pill" href="#address-book">Address Book</a></li>
        <li role="presentation"><%= link_to "Edit Profile", edit_user_registration_path %></li>
      </ul>
    </div>
    <div class="col-md-8">
      <div class="tab-content">
        <div id="overview" class="tab-pane fade in active">
          <h3>Hello <%= current_user.fullname %></h3>
          <% if current_user.orders.present? %>
          <div class="panel-default"> 
            <div class="panel-heading address-title">
              <h4>Your delivery is scheduled for: <%= current_user.orders.last.delivery_date %></h4>
            </div>
            <div class="panel-body">
              <%= current_user.orders.last.address.company_name %>,
              <%= current_user.orders.last.address.address_line_1 %>,
              <%= current_user.orders.last.address.post_code %>
            </div>
            <div class="panel-footer"></div>
            <br>
            <p><%= link_to "Order Again", new_order_path, class: "btn btn-default btn-md" %></p>
          <% else %>
            <%= "You haven't ordered yet" %>
            <br>
            <p><%= link_to "Order Now", new_order_path, class: "btn btn-default btn-md" %></p>
          <% end %>
        </div>
        </div>
        <div id="order-history" class="tab-pane fade">
          <h3>Order History</h3>
          <% if current_user.addresses.present? %>
            <% current_user.orders.reverse.each do |order| %>
              <div class="panel-default address-default">  
                <div class="panel-heading address-title">
                  <h5><%= order.address.company_name %></h5>
                </div>
                <div class="panel-body address-body">
                  <%= order.delivery_date %>,
                  <%= order.address.address_line_1 %>,
                  <%= order.address.post_code %>
                </div>
                  <div class="panel-footer address">
                <div></div>
                </div>
              </div>
              <br>
              <p><%= link_to "Order Beers", new_order_path, class: "btn btn-default btn-md" %></p>
            <% end %>
          <% else %>
            <h5>Sorry you have no addresses saved to your account, please add an address before you place an order</h5>
            <p><%= link_to "Add New Address", new_address_path, class: "btn btn-default btn-md" %></p>
          <% end %>
        </div>
        <br>
        <div id="address-book" class="tab-pane fade">
          <h3>My Address Book</h3>
          <% current_user.addresses.each do |address| %>
          <div class="panel-default address-default">  
            <div class="panel-heading address-title">
              <%= address.company_name %>
            </div>
            <div class="panel-body address-body">
              <%= address.address_line_1 %>,
              <%= address.address_line_2 %>,
              <%= address.city %>,
              <%= address.post_code %>
            </div>

            <div class="panel-footer address">
            <div></div>
            </div>
          </div>
          <br>
          <% end %>
          <p><%= link_to "Add New Address", new_address_path, class: "btn btn-default btn-md" %></p>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
    <!-- <h1>Hello, world!</h1> -->
    <%= image_tag "logo-main.png", class: "img-responsive" %>
    <p><%= link_to "Buy Beers Now!", new_order_path, class: "btn btn-default btn-lg" %></p>
</div>

<%= render 'about' %>

<div class="jumbotron beers">
    <h1>Ultimate Craft Beer Delivery Service</h1>
    <p><%= link_to "Order Beers Now", new_order_path, class: "btn btn-default btn-lg" %></p>
</div>

<div class="container" id="company">
  <div class="row">
    <div class="col-sm-12">
      <h2>Companies That Use DeskBrews</h2>
    </div>
  </div>
  <div class="row companies">
    <div class="col-md-4"><%= image_tag "one2date_logo.png" %></div>
    <div class="col-md-4"><%= image_tag "ga_logo.png" %></div>
    <div class="col-md-4"><%= image_tag "quintisocial_logo.png" %></div>
  </div>
</div>

<%= render "footer" %>

app/views/pages/how_it_works.html.erb
<%= render 'about' %>

<%= render "footer" %>